"""Change Unique constraint Category

Revision ID: 066fe01aa5d7
Revises: f348d7009399
Create Date: 2026-03-14 18:19:40.767178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066fe01aa5d7'
down_revision: Union[str, Sequence[str], None] = 'f348d7009399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_category_title'), 'category', type_='unique')
    op.create_unique_constraint('uq_tb-category_title_parent_id', 'category', ['title', 'parent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tb-category_title_parent_id', 'category', type_='unique')
    op.create_unique_constraint(op.f('uq_category_title'), 'category', ['title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
