"""Initial

Revision ID: 2ce398046817
Revises: 
Create Date: 2026-02-11 20:31:54.238606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ce398046817'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], name=op.f('fk_category_parent_id_category'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('title', name=op.f('uq_category_title'))
    )
    op.create_index(op.f('ix_category_parent_id'), 'category', ['parent_id'], unique=False)
    op.create_index(op.f('ix_category_slug'), 'category', ['slug'], unique=True)
    op.create_table('supplier',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint("inn ~ '^[0-9]*$'", name=op.f('ck_supplier_`chk_supplier_inn`')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier'))
    )
    op.create_index(op.f('ix_supplier_inn'), 'supplier', ['inn'], unique=True)
    op.create_index(op.f('ix_supplier_title'), 'supplier', ['title'], unique=False)
    op.create_table('user',
    sa.Column('first_name', sa.String(length=61), nullable=False),
    sa.Column('last_name', sa.String(length=61), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('installer', 'manager', 'storekeeper', 'client', name='enum_user_role'), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('cart',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_cart_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart')),
    sa.UniqueConstraint('user_id', name=op.f('uq_cart_user_id'))
    )
    op.create_table('characteristic',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('type', postgresql.ENUM('integer', 'float', 'string', 'boolean', name='enum_characteristic_type'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_characteristic_category_id_category'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_characteristic')),
    sa.UniqueConstraint('title', 'category_id', name='uq_tb-characteristic_title_category_id')
    )
    op.create_index(op.f('ix_characteristic_category_id'), 'characteristic', ['category_id'], unique=False)
    op.create_table('order',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('status', postgresql.ENUM('accepted', 'assembled', 'delivery', 'completed', 'cancelled', name='enum_order_status'), nullable=True),
    sa.Column('is_payment', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_order_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order'))
    )
    op.create_table('product',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('price > 0', name=op.f('ck_product_`chk_product_price`')),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_product_category_id_category'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_slug'), 'product', ['slug'], unique=True)
    op.create_index(op.f('ix_product_title'), 'product', ['title'], unique=True)
    op.create_table('supplies',
    sa.Column('document_number', sa.String(length=61), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('document_data', sa.Date(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('create_user_id', sa.Integer(), nullable=True),
    sa.Column('update_user_id', sa.Integer(), nullable=True),
    sa.Column('draft', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_user_id'], ['user.id'], name=op.f('fk_supplies_create_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_supplies_supplier_id_supplier'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['update_user_id'], ['user.id'], name=op.f('fk_supplies_update_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplies'))
    )
    op.create_table('cart_product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_cart_product_`chk_quantity_cart_product`')),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name=op.f('fk_cart_product_cart_id_cart'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_cart_product_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_product')),
    sa.UniqueConstraint('product_id', 'cart_id', name='uq_product_id_cart_id_cart_product')
    )
    op.create_table('characteristic_product',
    sa.Column('characteristic_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristic.id'], name=op.f('fk_characteristic_product_characteristic_id_characteristic'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_characteristic_product_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_characteristic_product')),
    sa.UniqueConstraint('characteristic_id', 'product_id', name='uq_characteristic_product')
    )
    op.create_index(op.f('ix_characteristic_product_characteristic_id'), 'characteristic_product', ['characteristic_id'], unique=False)
    op.create_index(op.f('ix_characteristic_product_product_id'), 'characteristic_product', ['product_id'], unique=False)
    op.create_table('order_product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), sa.Computed('quantity * price', ), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('price > 0', name=op.f('ck_order_product_`chk_order_product_price`')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_product_`chk_order_product_quantity`')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_order_product_order_id_order'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_order_product_product_id_product'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_product'))
    )
    op.create_table('supplies_product',
    sa.Column('supplies_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), sa.Computed('price * quantity', ), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('price > 0', name=op.f('ck_supplies_product_`chk_supplies_product_price`')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_supplies_product_`chk_supplies_product_quantity`')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_supplies_product_product_id_product'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplies_id'], ['supplies.id'], name=op.f('fk_supplies_product_supplies_id_supplies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplies_product')),
    sa.UniqueConstraint('supplies_id', 'product_id', name='uq_supplies_product__supplies_product')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplies_product')
    op.drop_table('order_product')
    op.drop_index(op.f('ix_characteristic_product_product_id'), table_name='characteristic_product')
    op.drop_index(op.f('ix_characteristic_product_characteristic_id'), table_name='characteristic_product')
    op.drop_table('characteristic_product')
    op.drop_table('cart_product')
    op.drop_table('supplies')
    op.drop_index(op.f('ix_product_title'), table_name='product')
    op.drop_index(op.f('ix_product_slug'), table_name='product')
    op.drop_index(op.f('ix_product_category_id'), table_name='product')
    op.drop_table('product')
    op.drop_table('order')
    op.drop_index(op.f('ix_characteristic_category_id'), table_name='characteristic')
    op.drop_table('characteristic')
    op.drop_table('cart')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_supplier_title'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_inn'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_category_slug'), table_name='category')
    op.drop_index(op.f('ix_category_parent_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
