"""CartProduct unique constraint p_id c_id

Revision ID: 39bc45b328b8
Revises: fdc9d198d881
Create Date: 2026-01-19 21:30:36.626250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39bc45b328b8'
down_revision: Union[str, Sequence[str], None] = 'fdc9d198d881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_product_id_cart_id_cart_product', 'cart_product', ['product_id', 'cart_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_id_cart_id_cart_product', 'cart_product', type_='unique')
    # ### end Alembic commands ###
