"""CheckCounstraint, UniqueConstraint CharacteristicProduct

Revision ID: 43d2b8c02ced
Revises: ef9a4e29e4f3
Create Date: 2025-12-11 19:53:03.434355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d2b8c02ced'
down_revision: Union[str, Sequence[str], None] = 'ef9a4e29e4f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_characteristic_productl', 'characteristic_product', ['characteristic_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_characteristic_productl', 'characteristic_product', type_='unique')
    # ### end Alembic commands ###
