"""Triggers

Revision ID: 57dd7b66466c
Revises: a79ce81663af
Create Date: 2026-01-12 20:27:39.127648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '57dd7b66466c'
down_revision: Union[str, Sequence[str], None] = 'a79ce81663af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_update_supplies_product_fn = PGFunction(
        schema="public",
        signature="update_supplies_product_fn()",
        definition="RETURNS TRIGGER AS $$\nDECLARE\n    final_quantity INT;\n    is_draft BOOLEAN;\nBEGIN\n    -- Skip change product quantity if draft supplies\n    SELECT s.draft\n    INTO is_draft\n    FROM supplies s\n    WHERE s.id = NEW.supplies_id;\n    \n    IF is_draft THEN\n        RETURN NEW;\n    END IF;\n    IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') THEN\n        IF (TG_OP = 'UPDATE') THEN\n            -- FOR UPDATE.\n            SELECT p.quantity - OLD.quantity + NEW.quantity\n            INTO final_quantity\n            FROM product p\n            WHERE p.id = NEW.product_id;\n        ELSIF (TG_OP = 'INSERT') THEN\n            -- FOR INSERT.\n            SELECT p.quantity + NEW.quantity\n            INTO final_quantity\n            FROM product p\n            WHERE p.id = NEW.product_id;\n        ELSE\n            -- FOR DELETE.\n            SELECT p.quantity - OLD.quantity\n            INTO final_quantity\n            FROM product p\n            WHERE p.id = NEW.product_id;\n        END IF;\n\n        -- CHECK\\: final_quantity >= 0\n        IF final_quantity IS NULL THEN\n            RAISE EXCEPTION 'Product not found.';\n        ELSIF final_quantity < 0 THEN\n            RAISE EXCEPTION 'Not enough products. Operation leads to a negative remainder';\n        END IF;\n\n        IF (TG_OP = 'UPDATE') THEN\n            UPDATE product\n            SET quantity = final_quantity\n            WHERE id = NEW.product_id;\n        ELSIF (TG_OP = 'INSERT') THEN\n            UPDATE product\n            SET quantity = final_quantity\n            WHERE id = NEW.product_id;\n        ELSE \n            UPDATE product\n            SET quantity = final_quantity\n            WHERE id = NEW.product_id;\n        END IF;\n    END IF;\n RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql"
    )
    op.create_entity(public_update_supplies_product_fn)

    public_update_supplies_draft_fn = PGFunction(
        schema="public",
        signature="update_supplies_draft_fn()",
        definition="RETURNS TRIGGER AS $$\nBEGIN\n    IF (TG_OP = 'UPDATE') THEN\n        IF (NEW.draft != OLD.draft) THEN\n            IF (NEW.draft = TRUE) THEN\n                IF NOT EXISTS (\n                        SELECT 1\n                        FROM supplies_product sp\n                        JOIN product p ON p.id = sp.product_id\n                        WHERE sp.supplies_id = NEW.id AND p.quantity <= sp.quantity\n                    ) THEN\n                        UPDATE product p\n                        SET quantity = p.quantity - sp.quantity\n                        FROM supplies_product sp\n                        WHERE sp.supplies_id = NEW.id AND p.id = sp.product_id;\n                    ELSE\n                        RAISE EXCEPTION 'Not enough products. Is Draft leads to a negative remainder';\n                    END IF;\n                END IF;\n                IF (NEW.draft = FALSE) THEN\n                    UPDATE product p\n                    SET quantity = p.quantity + sp.quantity\n                    FROM supplies_product sp\n                    WHERE sp.supplies_id = NEW.id AND p.id = sp.product_id;\n                END IF;\n            END IF;\n        END IF;\n    RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql"
    )
    op.create_entity(public_update_supplies_draft_fn)

    public_supplies_product_supplies_product_insert_tg = PGTrigger(
        schema="public",
        signature="supplies_product_insert_tg",
        on_entity="public.supplies_product",
        is_constraint=False,
        definition='AFTER INSERT ON supplies_product\n        FOR EACH ROW\n        EXECUTE FUNCTION update_supplies_product_fn()'
    )
    op.create_entity(public_supplies_product_supplies_product_insert_tg)

    public_supplies_product_supplies_product_update_tg = PGTrigger(
        schema="public",
        signature="supplies_product_update_tg",
        on_entity="public.supplies_product",
        is_constraint=False,
        definition='AFTER UPDATE ON supplies_product\n        FOR EACH ROW\n        EXECUTE FUNCTION update_supplies_product_fn()'
    )
    op.create_entity(public_supplies_product_supplies_product_update_tg)

    public_supplies_product_supplies_product_delete_tg = PGTrigger(
        schema="public",
        signature="supplies_product_delete_tg",
        on_entity="public.supplies_product",
        is_constraint=False,
        definition='AFTER DELETE ON supplies_product\n        FOR EACH ROW\n        EXECUTE FUNCTION update_supplies_product_fn()'
    )
    op.create_entity(public_supplies_product_supplies_product_delete_tg)

    public_supplies_update_supplies_draft_tg = PGTrigger(
        schema="public",
        signature="update_supplies_draft_tg",
        on_entity="public.supplies",
        is_constraint=False,
        definition='AFTER UPDATE ON supplies\n        FOR EACH ROW\n        EXECUTE FUNCTION update_supplies_draft_fn()'
    )
    op.create_entity(public_supplies_update_supplies_draft_tg)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_supplies_update_supplies_draft_tg = PGTrigger(
        schema="public",
        signature="update_supplies_draft_tg",
        on_entity="public.supplies",
        is_constraint=False,
        definition='AFTER UPDATE ON supplies\n        FOR EACH ROW\n        EXECUTE FUNCTION update_supplies_draft_fn()'
    )
    op.drop_entity(public_supplies_update_supplies_draft_tg)

    public_supplies_product_supplies_product_delete_tg = PGTrigger(
        schema="public",
        signature="supplies_product_delete_tg",
        on_entity="public.supplies_product",
        is_constraint=False,
        definition='AFTER DELETE ON supplies_product\n        FOR EACH ROW\n        EXECUTE FUNCTION update_supplies_product_fn()'
    )
    op.drop_entity(public_supplies_product_supplies_product_delete_tg)

    public_supplies_product_supplies_product_update_tg = PGTrigger(
        schema="public",
        signature="supplies_product_update_tg",
        on_entity="public.supplies_product",
        is_constraint=False,
        definition='AFTER UPDATE ON supplies_product\n        FOR EACH ROW\n        EXECUTE FUNCTION update_supplies_product_fn()'
    )
    op.drop_entity(public_supplies_product_supplies_product_update_tg)

    public_supplies_product_supplies_product_insert_tg = PGTrigger(
        schema="public",
        signature="supplies_product_insert_tg",
        on_entity="public.supplies_product",
        is_constraint=False,
        definition='AFTER INSERT ON supplies_product\n        FOR EACH ROW\n        EXECUTE FUNCTION update_supplies_product_fn()'
    )
    op.drop_entity(public_supplies_product_supplies_product_insert_tg)

    public_update_supplies_draft_fn = PGFunction(
        schema="public",
        signature="update_supplies_draft_fn()",
        definition="RETURNS TRIGGER AS $$\nBEGIN\n    IF (TG_OP = 'UPDATE') THEN\n        IF (NEW.draft != OLD.draft) THEN\n            IF (NEW.draft = TRUE) THEN\n                IF NOT EXISTS (\n                        SELECT 1\n                        FROM supplies_product sp\n                        JOIN product p ON p.id = sp.product_id\n                        WHERE sp.supplies_id = NEW.id AND p.quantity <= sp.quantity\n                    ) THEN\n                        UPDATE product p\n                        SET quantity = p.quantity - sp.quantity\n                        FROM supplies_product sp\n                        WHERE sp.supplies_id = NEW.id AND p.id = sp.product_id;\n                    ELSE\n                        RAISE EXCEPTION 'Not enough products. Is Draft leads to a negative remainder';\n                    END IF;\n                END IF;\n                IF (NEW.draft = FALSE) THEN\n                    UPDATE product p\n                    SET quantity = p.quantity + sp.quantity\n                    FROM supplies_product sp\n                    WHERE sp.supplies_id = NEW.id AND p.id = sp.product_id;\n                END IF;\n            END IF;\n        END IF;\n    RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql"
    )
    op.drop_entity(public_update_supplies_draft_fn)

    public_update_supplies_product_fn = PGFunction(
        schema="public",
        signature="update_supplies_product_fn()",
        definition="RETURNS TRIGGER AS $$\nDECLARE\n    final_quantity INT;\n    is_draft BOOLEAN;\nBEGIN\n    -- Skip change product quantity if draft supplies\n    SELECT s.draft\n    INTO is_draft\n    FROM supplies s\n    WHERE s.id = NEW.supplies_id;\n    \n    IF is_draft THEN\n        RETURN NEW;\n    END IF;\n    IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') THEN\n        IF (TG_OP = 'UPDATE') THEN\n            -- FOR UPDATE.\n            SELECT p.quantity - OLD.quantity + NEW.quantity\n            INTO final_quantity\n            FROM product p\n            WHERE p.id = NEW.product_id;\n        ELSIF (TG_OP = 'INSERT') THEN\n            -- FOR INSERT.\n            SELECT p.quantity + NEW.quantity\n            INTO final_quantity\n            FROM product p\n            WHERE p.id = NEW.product_id;\n        ELSE\n            -- FOR DELETE.\n            SELECT p.quantity - OLD.quantity\n            INTO final_quantity\n            FROM product p\n            WHERE p.id = NEW.product_id;\n        END IF;\n\n        -- CHECK\\: final_quantity >= 0\n        IF final_quantity IS NULL THEN\n            RAISE EXCEPTION 'Product not found.';\n        ELSIF final_quantity < 0 THEN\n            RAISE EXCEPTION 'Not enough products. Operation leads to a negative remainder';\n        END IF;\n\n        IF (TG_OP = 'UPDATE') THEN\n            UPDATE product\n            SET quantity = final_quantity\n            WHERE id = NEW.product_id;\n        ELSIF (TG_OP = 'INSERT') THEN\n            UPDATE product\n            SET quantity = final_quantity\n            WHERE id = NEW.product_id;\n        ELSE \n            UPDATE product\n            SET quantity = final_quantity\n            WHERE id = NEW.product_id;\n        END IF;\n    END IF;\n RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql"
    )
    op.drop_entity(public_update_supplies_product_fn)

    # ### end Alembic commands ###
