"""Characteristic add Unique constraint

Revision ID: 5bb87dc385b6
Revises: 43d2b8c02ced
Create Date: 2025-12-15 20:59:11.384721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb87dc385b6'
down_revision: Union[str, Sequence[str], None] = '43d2b8c02ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tb-characteristic_title_category_id', 'characteristic', ['title', 'category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tb-characteristic_title_category_id', 'characteristic', type_='unique')
    # ### end Alembic commands ###
