"""check triggers

Revision ID: 5c6dfb1c632d
Revises: 9e7e9878287d
Create Date: 2026-01-07 14:51:47.127178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '5c6dfb1c632d'
down_revision: Union[str, Sequence[str], None] = '9e7e9878287d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_update_warehouse_from_supplies = PGFunction(
        schema="public",
        signature="update_warehouse_from_supplies()",
        definition="RETURNS TRIGGER AS $$\nBEGIN\n    IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') THEN\n        IF (TG_OP = 'UPDATE') THEN\n            UPDATE warehouse\n            SET quantity = warehouse.quantity - OLD.quantity\n            WHERE product_id = OLD.product_id;\n        END IF;\n\n        INSERT INTO warehouse (product_id, quantity)\n        VALUES (NEW.product_id, NEW.quantity)\n        ON CONFLICT (product_id) DO UPDATE\n        SET quantity = warehouse.quantity + NEW.quantity;\n    END IF;\n\n    IF (TG_OP = 'DELETE') THEN\n        UPDATE warehouse\n        SET quantity = warehouse.quantity - OLD.quantity\n        WHERE product_id = OLD.product_id;\n\n        IF (SELECT quantity FROM warehouse WHERE product_id = OLD.product_id) < 0 THEN\n            RAISE EXCEPTION 'Not enough supplies to remove the cargo';\n        END IF;\n    END IF;\n\n    RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql"
    )
    op.replace_entity(public_update_warehouse_from_supplies)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_update_warehouse_from_supplies = PGFunction(
        schema="public",
        signature="update_warehouse_from_supplies()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\nBEGIN\n    IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') THEN\n        INSERT INTO warehouse (product_id, quantity)\n        VALUES (NEW.product_id, NEW.quantity)\n        ON CONFLICT (product_id) DO UPDATE\n        SET quantity = warehouse.quantity + NEW.quantity;\n    END IF;\n\n    IF (TG_OP = 'DELETE') THEN\n        UPDATE warehouse\n        SET quantity = warehouse.quantity - OLD.quantity\n        WHERE product_id = OLD.product_id;\n\n        IF (SELECT quantity FROM warehouse WHERE product_id = OLD.product_id) < 0 THEN\n            RAISE EXCEPTION 'Not enough supplies to remove the cargo';\n        END IF;\n    END IF;\n\n    RETURN NEW;\nEND;\n$function$"
    )
    op.replace_entity(public_update_warehouse_from_supplies)
    # ### end Alembic commands ###
