"""Drop Station

Revision ID: 5d05bd51cfc0
Revises: 764d2719e635
Create Date: 2026-01-13 19:10:15.030401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d05bd51cfc0'
down_revision: Union[str, Sequence[str], None] = '764d2719e635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_station_address'), table_name='station')
    op.drop_table('station')
    op.drop_column('order', 'station_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_order_station_id_station'), 'order', 'station', ['station_id'], ['id'], ondelete='SET NULL')
    op.create_table('station',
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_station'))
    )
    op.create_index(op.f('ix_station_address'), 'station', ['address'], unique=False)
    # ### end Alembic commands ###
