"""Supplies update_user update-date

Revision ID: 5d8d8a7b3dc4
Revises: 94b159c0ae8e
Create Date: 2026-01-05 18:04:39.043251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8d8a7b3dc4'
down_revision: Union[str, Sequence[str], None] = '94b159c0ae8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('updated', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('supplies', sa.Column('create_user_id', sa.Integer(), nullable=True))
    op.add_column('supplies', sa.Column('update_user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('fk_supplies_user_id_user'), 'supplies', type_='foreignkey')
    op.create_foreign_key(op.f('fk_supplies_update_user_id_user'), 'supplies', 'user', ['update_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_supplies_create_user_id_user'), 'supplies', 'user', ['create_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('supplies', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_supplies_create_user_id_user'), 'supplies', type_='foreignkey')
    op.drop_constraint(op.f('fk_supplies_update_user_id_user'), 'supplies', type_='foreignkey')
    op.create_foreign_key(op.f('fk_supplies_user_id_user'), 'supplies', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('supplies', 'update_user_id')
    op.drop_column('supplies', 'create_user_id')
    op.drop_column('supplies', 'updated')
    # ### end Alembic commands ###
