"""add warehouse product trigger

Revision ID: 66ac44abc7dc
Revises: e9781d33a66c
Create Date: 2026-01-06 13:12:55.045540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '66ac44abc7dc'
down_revision: Union[str, Sequence[str], None] = 'e9781d33a66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_update_warehouse_from_supplies = PGFunction(
        schema="public",
        signature="update_warehouse_from_supplies()",
        definition="RETURNS TRIGGER AS $$\nBEGIN\n    IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') THEN\n        INSERT INTO warehouse (product_id, quantity)\n        VALUES (NEW.product_id, NEW.quantity)\n        ON CONFLICT (product_id) DO UPDATE\n        SET quantity = warehouse.quantity + NEW.quantity;\n    END IF;\n\n    IF (TG_OP = 'DELETE') THEN\n        UPDATE warehouse\n        SET quantity = warehouse.quantity - OLD.quantity\n        WHERE product_id = OLD.product_id;\n\n        IF (SELECT quantity FROM warehouse WHERE product_id = OLD.product_id) < 0 THEN\n            RAISE EXCEPTION 'Not enough supplies to remove the cargo';\n        END IF;\n    END IF;\n\n    RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql"
    )
    op.create_entity(public_update_warehouse_from_supplies)

    public_supplies_product_trigger_supplies_product_insert = PGTrigger(
        schema="public",
        signature="trigger_supplies_product_insert",
        on_entity="public.supplies_product",
        is_constraint=False,
        definition='AFTER INSERT ON supplies_product\n        FOR EACH ROW\n        EXECUTE FUNCTION update_warehouse_from_supplies()'
    )
    op.create_entity(public_supplies_product_trigger_supplies_product_insert)

    public_supplies_product_trigger_supplies_product_update = PGTrigger(
        schema="public",
        signature="trigger_supplies_product_update",
        on_entity="public.supplies_product",
        is_constraint=False,
        definition='AFTER UPDATE ON supplies_product\n        FOR EACH ROW\n        EXECUTE FUNCTION update_warehouse_from_supplies()'
    )
    op.create_entity(public_supplies_product_trigger_supplies_product_update)

    public_supplies_product_trigger_supplies_product_delete = PGTrigger(
        schema="public",
        signature="trigger_supplies_product_delete",
        on_entity="public.supplies_product",
        is_constraint=False,
        definition='AFTER DELETE ON supplies_product\n        FOR EACH ROW\n        EXECUTE FUNCTION update_warehouse_from_supplies()'
    )
    op.create_entity(public_supplies_product_trigger_supplies_product_delete)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_supplies_product_trigger_supplies_product_delete = PGTrigger(
        schema="public",
        signature="trigger_supplies_product_delete",
        on_entity="public.supplies_product",
        is_constraint=False,
        definition='AFTER DELETE ON supplies_product\n        FOR EACH ROW\n        EXECUTE FUNCTION update_warehouse_from_supplies()'
    )
    op.drop_entity(public_supplies_product_trigger_supplies_product_delete)

    public_supplies_product_trigger_supplies_product_update = PGTrigger(
        schema="public",
        signature="trigger_supplies_product_update",
        on_entity="public.supplies_product",
        is_constraint=False,
        definition='AFTER UPDATE ON supplies_product\n        FOR EACH ROW\n        EXECUTE FUNCTION update_warehouse_from_supplies()'
    )
    op.drop_entity(public_supplies_product_trigger_supplies_product_update)

    public_supplies_product_trigger_supplies_product_insert = PGTrigger(
        schema="public",
        signature="trigger_supplies_product_insert",
        on_entity="public.supplies_product",
        is_constraint=False,
        definition='AFTER INSERT ON supplies_product\n        FOR EACH ROW\n        EXECUTE FUNCTION update_warehouse_from_supplies()'
    )
    op.drop_entity(public_supplies_product_trigger_supplies_product_insert)

    public_update_warehouse_from_supplies = PGFunction(
        schema="public",
        signature="update_warehouse_from_supplies()",
        definition="RETURNS TRIGGER AS $$\nBEGIN\n    IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') THEN\n        INSERT INTO warehouse (product_id, quantity)\n        VALUES (NEW.product_id, NEW.quantity)\n        ON CONFLICT (product_id) DO UPDATE\n        SET quantity = warehouse.quantity + NEW.quantity;\n    END IF;\n\n    IF (TG_OP = 'DELETE') THEN\n        UPDATE warehouse\n        SET quantity = warehouse.quantity - OLD.quantity\n        WHERE product_id = OLD.product_id;\n\n        IF (SELECT quantity FROM warehouse WHERE product_id = OLD.product_id) < 0 THEN\n            RAISE EXCEPTION 'Not enough supplies to remove the cargo';\n        END IF;\n    END IF;\n\n    RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql"
    )
    op.drop_entity(public_update_warehouse_from_supplies)

    # ### end Alembic commands ###
