"""Corrected Triggers

Revision ID: 764d2719e635
Revises: 57dd7b66466c
Create Date: 2026-01-12 20:37:03.223797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '764d2719e635'
down_revision: Union[str, Sequence[str], None] = '57dd7b66466c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_update_supplies_draft_fn = PGFunction(
        schema="public",
        signature="update_supplies_draft_fn()",
        definition="RETURNS TRIGGER AS $$\nBEGIN\n    IF (TG_OP = 'UPDATE') THEN\n        IF (NEW.draft != OLD.draft) THEN\n            IF (NEW.draft = TRUE) THEN\n                IF NOT EXISTS (\n                        SELECT 1\n                        FROM supplies_product sp\n                        JOIN product p ON p.id = sp.product_id\n                        WHERE sp.supplies_id = NEW.id AND p.quantity < sp.quantity\n                    ) THEN\n                        UPDATE product p\n                        SET quantity = p.quantity - sp.quantity\n                        FROM supplies_product sp\n                        WHERE sp.supplies_id = NEW.id AND p.id = sp.product_id;\n                    ELSE\n                        RAISE EXCEPTION 'Not enough products. Is Draft leads to a negative remainder';\n                    END IF;\n                END IF;\n                IF (NEW.draft = FALSE) THEN\n                    UPDATE product p\n                    SET quantity = p.quantity + sp.quantity\n                    FROM supplies_product sp\n                    WHERE sp.supplies_id = NEW.id AND p.id = sp.product_id;\n                END IF;\n            END IF;\n        END IF;\n    RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql"
    )
    op.replace_entity(public_update_supplies_draft_fn)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_update_supplies_draft_fn = PGFunction(
        schema="public",
        signature="update_supplies_draft_fn()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\nBEGIN\n    IF (TG_OP = 'UPDATE') THEN\n        IF (NEW.draft != OLD.draft) THEN\n            IF (NEW.draft = TRUE) THEN\n                IF NOT EXISTS (\n                        SELECT 1\n                        FROM supplies_product sp\n                        JOIN product p ON p.id = sp.product_id\n                        WHERE sp.supplies_id = NEW.id AND p.quantity <= sp.quantity\n                    ) THEN\n                        UPDATE product p\n                        SET quantity = p.quantity - sp.quantity\n                        FROM supplies_product sp\n                        WHERE sp.supplies_id = NEW.id AND p.id = sp.product_id;\n                    ELSE\n                        RAISE EXCEPTION 'Not enough products. Is Draft leads to a negative remainder';\n                    END IF;\n                END IF;\n                IF (NEW.draft = FALSE) THEN\n                    UPDATE product p\n                    SET quantity = p.quantity + sp.quantity\n                    FROM supplies_product sp\n                    WHERE sp.supplies_id = NEW.id AND p.id = sp.product_id;\n                END IF;\n            END IF;\n        END IF;\n    RETURN NEW;\nEND;\n$function$"
    )
    op.replace_entity(public_update_supplies_draft_fn)
    # ### end Alembic commands ###
