"""supplies draft

Revision ID: 94b159c0ae8e
Revises: 8967d1e27411
Create Date: 2026-01-05 17:43:24.525190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b159c0ae8e'
down_revision: Union[str, Sequence[str], None] = '8967d1e27411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('draft', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplies', 'draft')
    # ### end Alembic commands ###
