"""sippliesProduct unique constraint

Revision ID: 9e7e9878287d
Revises: 66ac44abc7dc
Create Date: 2026-01-06 13:35:44.718194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7e9878287d'
down_revision: Union[str, Sequence[str], None] = '66ac44abc7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_supplies_product__supplies_product', 'supplies_product', ['supplies_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_supplies_product__supplies_product', 'supplies_product', type_='unique')
    # ### end Alembic commands ###
