"""Order status nullable

Revision ID: 9fa877ed6695
Revises: 5d05bd51cfc0
Create Date: 2026-01-15 18:27:12.959792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fa877ed6695'
down_revision: Union[str, Sequence[str], None] = '5d05bd51cfc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('accepted', 'assembled', 'moving supplies', 'delivery', 'delivered', 'completed', 'cancelled', name='enum_order_status'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('accepted', 'assembled', 'moving supplies', 'delivery', 'delivered', 'completed', 'cancelled', name='enum_order_status'),
               nullable=False)
    # ### end Alembic commands ###
