"""delete supplies cascade delete products in supplies document

Revision ID: c48b666da161
Revises: 5c6dfb1c632d
Create Date: 2026-01-07 14:54:49.898745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48b666da161'
down_revision: Union[str, Sequence[str], None] = '5c6dfb1c632d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_supplies_product_supplies_id_supplies'), 'supplies_product', type_='foreignkey')
    op.create_foreign_key(op.f('fk_supplies_product_supplies_id_supplies'), 'supplies_product', 'supplies', ['supplies_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_supplies_product_supplies_id_supplies'), 'supplies_product', type_='foreignkey')
    op.create_foreign_key(op.f('fk_supplies_product_supplies_id_supplies'), 'supplies_product', 'supplies', ['supplies_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
