"""Warehouse, sipplies

Revision ID: cd9e319a832d
Revises: b1f7855d5d33
Create Date: 2026-01-04 15:47:05.621622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd9e319a832d'
down_revision: Union[str, Sequence[str], None] = 'b1f7855d5d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier')),
    sa.UniqueConstraint('inn', name=op.f('uq_supplier_inn'))
    )
    op.create_table('supplies',
    sa.Column('document_number', sa.String(length=255), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('document_data', sa.Date(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_supplies_supplier_id_supplier'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_supplies_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplies'))
    )
    op.create_table('supplies_product',
    sa.Column('supplies_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), sa.Computed('price * quantity', ), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_supplies_product_product_id_product'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplies_id'], ['supplies.id'], name=op.f('fk_supplies_product_supplies_id_supplies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplies_product'))
    )
    op.create_table('warehouse',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_warehouse_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse')
    op.drop_table('supplies_product')
    op.drop_table('supplies')
    op.drop_table('supplier')
    # ### end Alembic commands ###
