"""trigger order is_active

Revision ID: db3961f50406
Revises: 9fa877ed6695
Create Date: 2026-01-15 19:30:54.460783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = 'db3961f50406'
down_revision: Union[str, Sequence[str], None] = '9fa877ed6695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_update_order_is_active_fn = PGFunction(
        schema="public",
        signature="update_order_is_active_fn()",
        definition="RETURNS TRIGGER AS $$\n    BEGIN\n        IF (TG_OP = 'UPDATE') THEN\n            IF (NEW.is_active != OLD.is_active) THEN\n                    IF (NEW.is_active = TRUE AND NEW.status is NULL) THEN\n                        IF NOT EXISTS (\n                                SELECT 1\n                                FROM order_product op\n                                JOIN product p ON p.id = op.product_id\n                                WHERE op.order_id = NEW.id AND p.quantity < op.quantity\n                            ) THEN\n                                UPDATE product p\n                                SET quantity = p.quantity - op.quantity\n                                FROM order_product op\n                                WHERE op.order_id = NEW.id AND p.id = op.product_id;\n                            ELSE\n                                RAISE EXCEPTION 'Not enough products. The order has been cancelled.';\n                            END IF;\n                        END IF;\n                    IF (NEW.is_active = FALSE AND NEW.status is NULL) THEN\n                        UPDATE product p\n                        SET quantity = p.quantity + op.quantity\n                        FROM order_product op\n                        WHERE op.order_id = NEW.id AND p.id = op.product_id;\n                    END IF;\n                END IF;\n            END IF;\n        RETURN NEW;\n    END;\n    $$ LANGUAGE plpgsql"
    )
    op.create_entity(public_update_order_is_active_fn)

    public_order_update_order_is_active_tg = PGTrigger(
        schema="public",
        signature="update_order_is_active_tg",
        on_entity="public.order",
        is_constraint=False,
        definition='AFTER UPDATE ON order\n        FOR EACH ROW\n        EXECUTE FUNCTION update_order_is_active_fn()'
    )
    op.create_entity(public_order_update_order_is_active_tg)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_order_update_order_is_active_tg = PGTrigger(
        schema="public",
        signature="update_order_is_active_tg",
        on_entity="public.order",
        is_constraint=False,
        definition='AFTER UPDATE ON order\n        FOR EACH ROW\n        EXECUTE FUNCTION update_order_is_active_fn()'
    )
    op.drop_entity(public_order_update_order_is_active_tg)

    public_update_order_is_active_fn = PGFunction(
        schema="public",
        signature="update_order_is_active_fn()",
        definition="RETURNS TRIGGER AS $$\n    BEGIN\n        IF (TG_OP = 'UPDATE') THEN\n            IF (NEW.is_active != OLD.is_active) THEN\n                    IF (NEW.is_active = TRUE AND NEW.status is NULL) THEN\n                        IF NOT EXISTS (\n                                SELECT 1\n                                FROM order_product op\n                                JOIN product p ON p.id = op.product_id\n                                WHERE op.order_id = NEW.id AND p.quantity < op.quantity\n                            ) THEN\n                                UPDATE product p\n                                SET quantity = p.quantity - op.quantity\n                                FROM order_product op\n                                WHERE op.order_id = NEW.id AND p.id = op.product_id;\n                            ELSE\n                                RAISE EXCEPTION 'Not enough products. The order has been cancelled.';\n                            END IF;\n                        END IF;\n                    IF (NEW.is_active = FALSE AND NEW.status is NULL) THEN\n                        UPDATE product p\n                        SET quantity = p.quantity + op.quantity\n                        FROM order_product op\n                        WHERE op.order_id = NEW.id AND p.id = op.product_id;\n                    END IF;\n                END IF;\n            END IF;\n        RETURN NEW;\n    END;\n    $$ LANGUAGE plpgsql"
    )
    op.drop_entity(public_update_order_is_active_fn)

    # ### end Alembic commands ###
