"""supplies draft trigger

Revision ID: e762c5b93ba3
Revises: c48b666da161
Create Date: 2026-01-07 16:24:16.588213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = 'e762c5b93ba3'
down_revision: Union[str, Sequence[str], None] = 'c48b666da161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_update_warehouse_draft_supplies = PGFunction(
        schema="public",
        signature="update_warehouse_draft_supplies()",
        definition="RETURNS TRIGGER AS $$\nBEGIN\n       IF (TG_OP = 'UPDATE') THEN\n            IF (NEW.draft != OLD.draft) THEN\n                IF (NEW.draft = TRUE) THEN\n                -- Проверяем, хватит ли запасов на складе для списания\n                    IF NOT EXISTS (\n                            SELECT 1\n                            FROM supplies_product sp\n                            JOIN warehouse w ON w.product_id = sp.product_id\n                            WHERE sp.supplies_id = NEW.id AND w.quantity < sp.quantity\n                        ) THEN\n                            UPDATE warehouse w\n                            SET quantity = w.quantity - sp.quantity\n                            FROM supplies_product sp\n                            WHERE sp.supplies_id = NEW.id AND w.product_id = sp.product_id;\n                        ELSE\n                        RAISE EXCEPTION 'There are not enough goods in the warehouse to process the document. ID %', NEW.id;\n                    END IF;\n                END IF;\n                IF (NEW.draft = FALSE) THEN\n                    UPDATE warehouse w\n                    SET quantity = w.quantity + sp.quantity\n                    FROM supplies_product sp\n                    WHERE sp.supplies_id = 4 AND w.product_id = sp.product_id;\n                END IF;\n            END IF;\n        END IF;\n\n    RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql"
    )
    op.create_entity(public_update_warehouse_draft_supplies)

    public_supplies_trigger_supplies_update = PGTrigger(
        schema="public",
        signature="trigger_supplies_update",
        on_entity="public.supplies",
        is_constraint=False,
        definition='AFTER UPDATE ON supplies\n        FOR EACH ROW\n        EXECUTE FUNCTION update_warehouse_draft_supplies()'
    )
    op.create_entity(public_supplies_trigger_supplies_update)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_supplies_trigger_supplies_update = PGTrigger(
        schema="public",
        signature="trigger_supplies_update",
        on_entity="public.supplies",
        is_constraint=False,
        definition='AFTER UPDATE ON supplies\n        FOR EACH ROW\n        EXECUTE FUNCTION update_warehouse_draft_supplies()'
    )
    op.drop_entity(public_supplies_trigger_supplies_update)

    public_update_warehouse_draft_supplies = PGFunction(
        schema="public",
        signature="update_warehouse_draft_supplies()",
        definition="RETURNS TRIGGER AS $$\nBEGIN\n       IF (TG_OP = 'UPDATE') THEN\n            IF (NEW.draft != OLD.draft) THEN\n                IF (NEW.draft = TRUE) THEN\n                -- Проверяем, хватит ли запасов на складе для списания\n                    IF NOT EXISTS (\n                            SELECT 1\n                            FROM supplies_product sp\n                            JOIN warehouse w ON w.product_id = sp.product_id\n                            WHERE sp.supplies_id = NEW.id AND w.quantity < sp.quantity\n                        ) THEN\n                            UPDATE warehouse w\n                            SET quantity = w.quantity - sp.quantity\n                            FROM supplies_product sp\n                            WHERE sp.supplies_id = NEW.id AND w.product_id = sp.product_id;\n                        ELSE\n                        RAISE EXCEPTION 'There are not enough goods in the warehouse to process the document. ID %', NEW.id;\n                    END IF;\n                END IF;\n                IF (NEW.draft = FALSE) THEN\n                    UPDATE warehouse w\n                    SET quantity = w.quantity + sp.quantity\n                    FROM supplies_product sp\n                    WHERE sp.supplies_id = 4 AND w.product_id = sp.product_id;\n                END IF;\n            END IF;\n        END IF;\n\n    RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql"
    )
    op.drop_entity(public_update_warehouse_draft_supplies)

    # ### end Alembic commands ###
