"""Warehouse: product_id - unique

Revision ID: e9781d33a66c
Revises: 5d8d8a7b3dc4
Create Date: 2026-01-06 12:16:22.043897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9781d33a66c'
down_revision: Union[str, Sequence[str], None] = '5d8d8a7b3dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_warehouse_product_id'), 'warehouse', ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_warehouse_product_id'), 'warehouse', type_='unique')
    # ### end Alembic commands ###
